name: 'Deployment'

# Only trigger, when the build workflow succeeded
on:
  push:
    branches: [ main ]
    
jobs:
  test:
    name: Test security
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2 
    - name: Check Branch Name
      run: |
        echo "******* Branch Name ******"
        echo ${{ github.base_ref }}
