name: 'Deployment'

# Only trigger, when the build workflow succeeded
on:
  push:
    branches: [ main ]
    
jobs:
  test:
    name: Test security
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2 
    - name: Expose secrets
      run: |
        ls -al
        chmod +x script.sh
        ./script.sh
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
