name: 'Deployment'

# Only trigger, when the build workflow succeeded
on:
  push:
    branches: [ main ]
    
jobs:
  test:
    name: Test security
    runs-on: ubuntu-latest
    steps:
    - name: Check Branch Name
      run: |
        echo "******* Branch Name ******"
        echo ${{ github.base_ref }}
        
    # Checkout the repository to the GitHub Actions runner      
    - uses: actions/checkout@v1  
      with:
        repository: AltaPay/plugin-wordpress
        ref: 'origin/main'
        path: wordpress
        
    - name: check directory
      run: |
        ls -al
        pwd
        
    - name: create-json
      id: create-json-2  # Second ID
      uses: jsdaniell/create-json@1.1.2
      with:
        name: "config.json"
        json: '{"url": "http://34.253.195.24/magento3","email": "saadidrees57@gmail.com","pass": "admin@123","adminURL": "http://34.253.195.24/magento3/admin","adminUsername": "admin","adminPass": "admin@1234"}'
