name: PHP Composer

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install composer and add dependencies
      uses: php-actions/composer@v4
    - run: sudo composer require --dev prestashop/php-dev-tools
    - run: sudo composer global require phpstan/phpstan:^0.12
    - uses: actions/checkout@v2
    - run: php vendor/bin/prestashop-coding-standards cs-fixer:init --dest TestRepo
    - run: php vendor/bin/prestashop-coding-standards phpstan:init --dest TestRepo



    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    # - name: Run test suite
    #   run: composer run-script test
