name: PHP Composer

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Pull repo
      uses: actions/checkout@v2
    - name: Install composer and add dependencies
      uses: php-actions/composer@v4
    
    - run: sudo composer require --dev prestashop/php-dev-tools
    - run: sudo composer global require phpstan/phpstan:^0.12
    - run: sudo cp vendor/prestashop/php-dev-tools/phpstan/ps-module-extension.neon vendor/prestashop/php-dev-tools/phpstan/extension.neon
    - run: sudo cp vendor/prestashop/php-dev-tools/templates/phpstan/phpstan.neon phpstan.neon
    - run: sudo chown -R $USER:$USER phpstan.neon
    - run: sudo echo '  excludes_analyse:' >> phpstan.neon
    - run: sudo echo '    - %currentWorkingDirectory%/vendor/*' >> phpstan.neon
    - run: _PS_ROOT_DIR_=./ php ~/.composer/vendor/bin/phpstan.phar --configuration=phpstan.neon analyse ./
    

    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    # - name: Run test suite
    #   run: composer run-script test
